import { ArrowUpRight, Check } from "lucide-react";
import { Link } from "wouter";
import SiteLayout, { CTASection, PageIntro } from "@/components/SiteLayout";

export default function About() {
  return <SiteLayout><main><PageIntro eyebrow="02 / ABOUT BONNE TRINITY" title={<>A newer venture, <i>grounded in experience.</i></>} text="BONNE TRINITY is a New Delhi-based B2B partnership led by Gavish Aneja and Hriday Aneja. We develop, source, private-label, supply and distribute through trusted manufacturing and sourcing partners." />
    <section className="about-story"><div className="container about-story-grid"><div><span className="section-label">OUR POINT OF VIEW</span><h2>Good products begin with <i>good listening.</i></h2></div><div className="about-body"><p>We work with brands, distributors, retailers and OEM clients who need a responsive partner for everyday care categories. Our role is to translate a brief into a practical product pathway — with clear communication from first conversation to supply.</p><p>We are not presenting BONNE TRINITY as a factory. We are a separate, newer company backed by established family manufacturing experience and a trusted network.</p><Link className="text-link" href="/enquire">Start a conversation <span>↗</span></Link></div></div></section>
    <section className="history-section"><div className="container"><div className="section-label">BACKED BY EXPERIENCE SINCE 1963</div><div className="history-grid"><div><h2>People, process<br /><i>and perspective.</i></h2></div><div className="history-list"><article><span>1998</span><div><h3>Bonny Baby Care Pvt. Ltd.</h3><p>Associated family business producing baby feeding bottles, nipples, silicone soothers, teethers and other baby-care products.</p></div></article><article><span>2001</span><div><h3>Bonny Poly Plast Pvt. Ltd.</h3><p>Associated family business producing baby feeding bottles, baby nipples and PET bottles.</p></div></article><article><span>NOW</span><div><h3>BONNE TRINITY</h3><p>A focused B2B partner connecting product thinking, trusted manufacturing and sourcing pathways.</p></div></article></div></div></div></section>
    <section className="principles-section"><div className="container"><div className="section-label">HOW WE WORK</div><div className="principles-grid"><div><Check /><h3>Clear briefs</h3><p>We ask the right questions early so product and sourcing conversations stay practical.</p></div><div><Check /><h3>Trusted partners</h3><p>We connect requirements to established manufacturing and sourcing relationships.</p></div><div><Check /><h3>Long-term thinking</h3><p>We build for repeat supply, private label growth and reliable partnerships.</p></div></div></div></section><CTASection /></main></SiteLayout>;
}
