import { FormEvent, useState } from "react";
import { ArrowUpRight, Mail, MessageCircle, Phone } from "lucide-react";
import { toast } from "sonner";
import SiteLayout, { PageIntro } from "@/components/SiteLayout";

export default function Enquire() {
  const [isSubmitting, setIsSubmitting] = useState(false); const [sent, setSent] = useState(false);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsSubmitting(true); const form = event.currentTarget; const data = new FormData(form); const accessKey = import.meta.env.VITE_WEB3FORMS_ACCESS_KEY || "YOUR_WEB3FORMS_ACCESS_KEY"; data.set("access_key", accessKey); data.set("subject", "New BONNE TRINITY website enquiry"); data.set("from_name", "BONNE TRINITY Website"); data.set("to", "bonnetrinity@gmail.com"); data.set("botcheck", ""); if (accessKey === "YOUR_WEB3FORMS_ACCESS_KEY") { toast.error("Add your Web3Forms access key to activate submissions."); setIsSubmitting(false); return; } try { const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: data }); const result = await response.json(); if (!result.success) throw new Error(result.message); setSent(true); form.reset(); toast.success("Thanks — your enquiry is on its way to BONNE TRINITY."); } catch { toast.error("Something went wrong. Please email care@bonnetrinity.com instead."); } finally { setIsSubmitting(false); } }
  return <SiteLayout><main><PageIntro eyebrow="04 / START A CONVERSATION" title={<>Tell us what you <i>need.</i></>} text="Share a product brief, sourcing requirement or distribution enquiry. We’ll come back with the right next questions." /><section className="enquire-page"><div className="container enquire-page-grid"><div className="enquire-contact"><span className="section-label">CONTACT BONNE TRINITY</span><h2>Let’s make something <i>useful.</i></h2><p>For product enquiries, private label, OEM and distribution conversations, reach out directly or use the form.</p><div className="contact-list"><a href="mailto:care@bonnetrinity.com"><Mail size={16} /> care@bonnetrinity.com</a><a href="tel:+919811643325"><Phone size={16} /> +91 98116 43325</a><a href="https://wa.me/918588879611" target="_blank" rel="noreferrer"><MessageCircle size={16} /> WhatsApp us</a></div></div><div className="form-card">{sent ? <div className="success-state"><h3>Thank you.</h3><p>We’ve received your enquiry and will be in touch shortly.</p><a className="text-link" href="/products">Explore products <span>↗</span></a></div> : <form onSubmit={handleSubmit}><div className="form-row"><label>Name<input name="name" required placeholder="Your name" /></label><label>Company<input name="company" required placeholder="Company name" /></label></div><div className="form-row"><label>Email<input name="email" type="email" required placeholder="you@company.com" /></label><label>Phone<input name="phone" required placeholder="+91" /></label></div><label>What can we help with?<textarea name="message" required rows={5} placeholder="Tell us about your product, category, MOQ or market." /></label><input className="hidden-field" name="botcheck" tabIndex={-1} autoComplete="off" /><div className="form-foot"><span>Your information is used only to respond to this enquiry.</span><button className="button button-dark" type="submit" disabled={isSubmitting}>{isSubmitting ? "Sending..." : "Send enquiry"} <ArrowUpRight size={17} /></button></div></form>}</div></div></section></main></SiteLayout>;
}
